spring:
  profiles:
    active: dev
---
server:
  port: 8080
  servlet:
    context-path: /integration
spring:
  profiles: dev
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
#      user: admin
#      password: password
      uri: mongodb://localhost:27017/grocery
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect