server:
  port: 8080
  servlet:
    context-path: /integration
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  data:
    mongodb:
      user: admin
      password: password
      uri: mongodb://host:27017/grocery
